# Generated by Django 4.2.6 on 2024-02-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atai_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
